name = "stasher-web"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Observability
observability = { enabled = true }

 [[routes]]
  pattern = "app.stasher.dev/*"
  zone_name = "stasher.dev"
