name = "stasher-web"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Observability
observability = { enabled = true }

# R2 Storage for assets
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "stasher-web-assets"

# Development environment
[env.dev]
name = "stasher-web-dev"