name: Web App Release & Signing

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Required for creating GitHub releases
      id-token: write      # Required for OIDC token generation (keyless signing)
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout stasher-ci for SLSA scripts
        uses: actions/checkout@v4
        with:
          repository: stasher-dev/stasher-ci
          path: stasher-ci

      - name: Setup Node.js
        uses: stasher-dev/stasher-ci/actions/setup-node@main
        with:
          node-version: '20'

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.2.2'

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0
        with:
          syft-version: 'v1.11.1'

      - name: Install Wrangler
        run: npm install -g wrangler@3

      - name: Build web app
        run: |
          echo "BUILD_START_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
          npm run build

      - name: Extract deployable Worker code and prepare bundles
        run: |
          # Phase 5: Use wrangler to extract the exact Worker bundle that would be deployed
          echo "🔍 Extracting deployable Worker code with wrangler dry-run..."
          mkdir -p worker-extracted
          
          # Wrangler dry-run to capture deployment metadata
          wrangler deploy --dry-run --outdir worker-extracted 2>&1 | tee wrangler-dry-run.log || true
          
          # Create the actual deployable worker bundle
          echo "📦 Creating deployable worker bundle..."
          mkdir -p deployable-worker
          
          # Copy the built worker.js (this is what actually gets deployed)
          cp dist/worker.js deployable-worker/worker.js
          cp wrangler.toml deployable-worker/wrangler.toml
          cp package.json deployable-worker/package.json
          
          # Generate deployment metadata with built artifact hash
          WORKER_CONTENT_HASH=$(sha256sum dist/worker.js | cut -d' ' -f1)
          COMMIT_SHA="${{ github.sha }}"
          
          echo "WORKER_CONTENT_HASH=$WORKER_CONTENT_HASH" >> $GITHUB_ENV
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
          
          # Create deployment metadata
          cat > deployable-worker/deployment-metadata.json << EOF
          {
            "worker_content_hash": "$WORKER_CONTENT_HASH",
            "commit_sha": "$COMMIT_SHA",
            "build_time": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "version": "$(node -p 'require(\"./package.json\").version')",
            "wrangler_version": "$(wrangler --version)",
            "built_artifact": "dist/worker.js"
          }
          EOF
          
          # Create tarball of the deployable worker bundle
          tar -czf stasher-web-app-deployable.tar.gz deployable-worker/
          echo "DEPLOYABLE_BUNDLE=stasher-web-app-deployable.tar.gz" >> $GITHUB_ENV
          
          # Also create source bundle with complete build artifacts for verification
          mkdir -p bundle
          cp -r dist/ bundle/
          cp -r src/ bundle/
          cp esbuild.config.js bundle/
          cp wrangler.toml bundle/
          cp package.json bundle/
          cp README.md bundle/
          cp LICENSE bundle/
          tar -czf stasher-web-app-bundle.tar.gz bundle/
          echo "BUNDLE_FILE=stasher-web-app-bundle.tar.gz" >> $GITHUB_ENV

      - name: Sign artifacts with Cosign
        run: |
          # Sign the web app bundle
          cosign sign-blob --yes ${{ env.BUNDLE_FILE }} --output-signature ${{ env.BUNDLE_FILE }}.sig
          
          # Sign individual built artifacts
          cosign sign-blob --yes dist/worker.js --output-signature dist/worker.js.sig
          cosign sign-blob --yes esbuild.config.js --output-signature esbuild.config.js.sig
          cosign sign-blob --yes wrangler.toml --output-signature wrangler.toml.sig
          
          # Generate checksums
          sha256sum ${{ env.BUNDLE_FILE }} dist/worker.js esbuild.config.js wrangler.toml > checksums.txt
          
          # Sign the checksums file
          cosign sign-blob --yes checksums.txt --output-signature checksums.txt.sig

      - name: Generate SLSA v1 Provenance Attestation
        env:
          RUNNER_VERSION: ${{ runner.os }}-${{ runner.arch }}
        run: |
          # Generate SLSA v1 predicate for the web app bundle
          node stasher-ci/scripts/generate-slsa-predicate.js ${{ env.BUNDLE_FILE }} slsa-predicate.json
          node stasher-ci/scripts/generate-slsa-predicate.js ${{ env.BUNDLE_FILE }} ${{ env.BUNDLE_FILE }}.predicate.intoto.jsonl
          
          # Create attestation using cosign attest-blob
          cosign attest-blob --yes \
            --type https://slsa.dev/provenance/v1 \
            --predicate ${{ env.BUNDLE_FILE }}.predicate.intoto.jsonl \
            --output-file ${{ env.BUNDLE_FILE }}.intoto.jsonl \
            ${{ env.BUNDLE_FILE }}
          
          echo "✅ SLSA v1 predicate generated: slsa-predicate.json (readable)"
          echo "✅ SLSA v1 predicate generated: ${{ env.BUNDLE_FILE }}.predicate.intoto.jsonl (cosign format)"
          echo "✅ SLSA v1 attestation created: ${{ env.BUNDLE_FILE }}.intoto.jsonl"

      - name: Generate SBOM with Syft
        run: |
          # Extract package info for SBOM generation
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          
          # Generate SPDX JSON SBOM including full transitive dependencies
          syft scan . \
            --output spdx-json=sbom.spdx.json
          
          echo "✅ SBOM generated: sbom.spdx.json"

      - name: Sign SBOM and create attestation
        run: |
          # Sign the SBOM with cosign
          cosign sign-blob --yes sbom.spdx.json --output-signature sbom.spdx.json.sig
          
          # Create SBOM attestation
          cosign attest-blob --yes \
            --type https://spdx.dev/Document \
            --predicate sbom.spdx.json \
            --output-file sbom.spdx.json.intoto.jsonl \
            sbom.spdx.json
          
          echo "✅ SBOM signed: sbom.spdx.json.sig"
          echo "✅ SBOM attestation created: sbom.spdx.json.intoto.jsonl"

      - name: Run npm audit (vulnerability scanning)
        run: |
          echo "🔍 Running vulnerability scan..."
          npm audit --audit-level=moderate --json > npm-audit.json || true
          
          # Show summary in logs
          if [ -s npm-audit.json ]; then
            echo "📊 Vulnerability scan results:"
            node -e "
              const audit = JSON.parse(require('fs').readFileSync('npm-audit.json'));
              if (audit.metadata) {
                console.log('Dependencies:', audit.metadata.totalDependencies);
                console.log('Vulnerabilities:', audit.metadata.vulnerabilities.total || 0);
                if (audit.metadata.vulnerabilities.total > 0) {
                  console.log('Breakdown:', JSON.stringify(audit.metadata.vulnerabilities, null, 2));
                }
              }
            "
          else
            echo "✅ No vulnerabilities found"
          fi

      - name: Extract package info
        id: package
        run: |
          echo "name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Prepare release files
        run: |
          # Collect all signature files and artifacts
          mkdir -p release-assets
          
          # Copy bundle and its signatures/attestations
          cp ${{ env.BUNDLE_FILE }} release-assets/
          cp ${{ env.BUNDLE_FILE }}.sig release-assets/
          cp ${{ env.BUNDLE_FILE }}.intoto.jsonl release-assets/
          cp ${{ env.BUNDLE_FILE }}.predicate.intoto.jsonl release-assets/
          
          # Copy individual file signatures
          cp dist/worker.js.sig release-assets/
          cp esbuild.config.js.sig release-assets/
          cp wrangler.toml.sig release-assets/
          
          # Copy built artifacts
          cp -r dist release-assets/
          
          # Copy SLSA predicate files
          cp slsa-predicate.json release-assets/
          
          # Copy SBOM files
          cp sbom.spdx.json release-assets/
          cp sbom.spdx.json.sig release-assets/
          cp sbom.spdx.json.intoto.jsonl release-assets/
          
          # Copy vulnerability scan results
          cp npm-audit.json release-assets/ 2>/dev/null || true
          
          # Copy checksums and signature
          cp checksums.txt release-assets/
          cp checksums.txt.sig release-assets/
          
          # List what we're releasing
          echo "Release assets:"
          ls -la release-assets/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ steps.package.outputs.name }} v${{ steps.package.outputs.version }}
          draft: false
          prerelease: false
          files: |
            release-assets/*
          body: |
            ## ${{ steps.package.outputs.name }} v${{ steps.package.outputs.version }}
            
            ### Stasher Web App Release
            This is a signed release of the Stasher Web App (browser-based secret sharing) with complete supply chain security.
            
            ### Cryptographic Verification
            This release is **signed with Cosign** using GitHub OIDC keyless signing and includes **SLSA v1 provenance attestation** + **SBOM**.
            
            **Verify the Web App bundle:**
            ```bash
            # Download the bundle and signature
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${{ env.BUNDLE_FILE }}
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${{ env.BUNDLE_FILE }}.sig
            
            # Verify signature
            cosign verify-blob --certificate-identity-regexp="https://github.com/${{ github.repository }}/.*" \
              --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
              --signature=${{ env.BUNDLE_FILE }}.sig \
              ${{ env.BUNDLE_FILE }}
            ```
            
            **Verify built Worker artifact:**
            ```bash
            # Download built worker and signature
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/dist/worker.js
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/worker.js.sig
            
            # Verify worker signature
            cosign verify-blob --certificate-identity-regexp="https://github.com/${{ github.repository }}/.*" \
              --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
              --signature=worker.js.sig \
              dist/worker.js
            ```
            
            **Verify SLSA v1 Provenance Attestation:**
            ```bash
            # Download the attestation
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${{ env.BUNDLE_FILE }}.intoto.jsonl
            
            # Verify attestation (requires slsa-verifier)
            # Install: go install github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier@latest
            slsa-verifier verify-artifact \
              --provenance-path ${{ env.BUNDLE_FILE }}.intoto.jsonl \
              --source-uri github.com/${{ github.repository }} \
              --source-tag ${{ github.ref_name }} \
              ${{ env.BUNDLE_FILE }}
            
            # Or verify with cosign (manual inspection)
            cosign verify-attestation \
              --certificate-identity-regexp="https://github.com/${{ github.repository }}/.*" \
              --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
              --type=https://slsa.dev/provenance/v1 \
              ${{ env.BUNDLE_FILE }}
            ```
            
            **Verify SBOM (Software Bill of Materials):**
            ```bash
            # Download SBOM and signature
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/sbom.spdx.json
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/sbom.spdx.json.sig
            
            # Verify SBOM signature
            cosign verify-blob \
              --certificate-identity-regexp="https://github.com/${{ github.repository }}/.*" \
              --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
              --signature=sbom.spdx.json.sig \
              sbom.spdx.json
            
            # Verify SBOM attestation
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/sbom.spdx.json.intoto.jsonl
            cosign verify-attestation \
              --certificate-identity-regexp="https://github.com/${{ github.repository }}/.*" \
              --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
              --type=https://spdx.dev/Document \
              sbom.spdx.json
            ```
            
            **Verify checksums:**
            ```bash
            # Download and verify checksums
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/checksums.txt
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/checksums.txt.sig
            cosign verify-blob --certificate-identity-regexp="https://github.com/${{ github.repository }}/.*" \
              --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
              --signature=checksums.txt.sig checksums.txt
            sha256sum -c checksums.txt
            ```
            
            ### 🏗️ What This Proves
            ✅ **Source Integrity** - Web app built from verified GitHub repository  
            ✅ **Build Authenticity** - Built by GitHub Actions with OIDC identity  
            ✅ **Supply Chain Security** - Complete build environment captured in attestation  
            ✅ **Provenance** - Traceable from TypeScript source to bundled JavaScript  
            ✅ **Transparency** - All signatures logged to public [Rekor](https://rekor.sigstore.dev) log  
            ✅ **Dependency Transparency** - Complete SBOM with all transitive dependencies  
            ✅ **License Compliance** - SPDX-compliant license identification  
            ✅ **Vulnerability Monitoring** - Automated security scanning integrated
            
            **Rekor Entry**: [Search for this release](https://search.sigstore.dev/?hash=${{ env.BUNDLE_FILE }})
            
            ### Usage
            This web app can be used directly in browser DevTools or deployed as a Cloudflare Worker. The signed bundle ensures you're running verified code.
            
            ### Changes
            See commit history for details of changes in this release.
            
            ---
            🔐 **Signed** | 🧾 **SLSA v1 Attested** | 📋 **SBOM Included** | 📜 **Logged to [Rekor](https://rekor.sigstore.dev)** | 🛡️ **Zero-Trust Verified**